# -*- coding: utf-8 -*-
"""IS and AE on NSL-KDD

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DeNHIuMQfbK0gbQcvPvVnHeq2UFu2IYF
"""

import os
os.environ["KERAS_BACKEND"] = "torch"

import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.ensemble import IsolationForest
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, precision_recall_fscore_support
from sklearn.decomposition import PCA

import keras
from keras import layers
import kagglehub

SEED = 42
random.seed(SEED)
np.random.seed(SEED)

print("Keras backend:", keras.backend.backend())

# ==========================================
# 1. Download & Load NSL-KDD Dataset
# ==========================================
print("Downloading NSL-KDD dataset...")
path = kagglehub.dataset_download("hassan06/nslkdd")
train_path = os.path.join(path, "KDDTrain+.txt")
test_path = os.path.join(path, "KDDTest+.txt")

columns = [
    'duration', 'protocol_type', 'service', 'flag', 'src_bytes', 'dst_bytes',
    'land', 'wrong_fragment', 'urgent', 'hot', 'num_failed_logins', 'logged_in',
    'num_compromised', 'root_shell', 'su_attempted', 'num_root', 'num_file_creations',
    'num_shells', 'num_access_files', 'num_outbound_cmds', 'is_host_login',
    'is_guest_login', 'count', 'srv_count', 'serror_rate', 'srv_serror_rate',
    'rerror_rate', 'srv_rerror_rate', 'same_srv_rate', 'diff_srv_rate',
    'srv_diff_host_rate', 'dst_host_count', 'dst_host_srv_count',
    'dst_host_same_srv_rate', 'dst_host_diff_srv_rate', 'dst_host_same_src_port_rate',
    'dst_host_srv_diff_host_rate', 'dst_host_serror_rate', 'dst_host_srv_serror_rate',
    'dst_host_rerror_rate', 'dst_host_srv_rerror_rate', 'attack', 'level'
]

train_df = pd.read_csv(train_path, header=None, names=columns)
test_df = pd.read_csv(test_path, header=None, names=columns)

# Define Binary Labels (0 = Normal, 1 = Attack)
train_df['is_attack'] = (train_df['attack'] != 'normal').astype(int)
test_df['is_attack'] = (test_df['attack'] != 'normal').astype(int)

train_df.drop(['attack', 'level'], axis=1, inplace=True)
test_df.drop(['attack', 'level'], axis=1, inplace=True)

categorical_cols = ['protocol_type', 'service', 'flag']
numeric_cols = [c for c in train_df.columns if c not in categorical_cols + ['is_attack']]

# ==========================================
# 2. Train / Val / Test Splits
# ==========================================
# We split the training set to get a validation set for the Autoencoder.
train_df, val_df = train_test_split(train_df, test_size=0.2, stratify=train_df["is_attack"], random_state=SEED)

# Filter ONLY normal traffic for Autoencoder training
normal_train_df = train_df[train_df["is_attack"] == 0].copy()
normal_val_df = val_df[val_df["is_attack"] == 0].copy()

print("Train shape:", train_df.shape, "| Normal-only AE train:", normal_train_df.shape)
print("Test shape:", test_df.shape)

# ==========================================
# 3. Model A — Isolation Forest
# ==========================================
print("\n--- Training Isolation Forest ---")
if_preprocessor = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), numeric_cols),
        ("cat", OneHotEncoder(handle_unknown="ignore", sparse_output=False), categorical_cols),
    ]
)

X_if_train = if_preprocessor.fit_transform(train_df[numeric_cols + categorical_cols])
X_if_test = if_preprocessor.transform(test_df[numeric_cols + categorical_cols])
y_test = test_df["is_attack"].to_numpy()

# IF doesn't allow contamination > 0.5. We bound it at 0.49
contamination_rate = min(0.49, float(train_df["is_attack"].mean()))

iso = IsolationForest(
    n_estimators=300,
    contamination=contamination_rate,
    random_state=SEED,
    n_jobs=-1
)
iso.fit(X_if_train)

if_score = -iso.decision_function(X_if_test)
if_pred = (iso.predict(X_if_test) == -1).astype(int)

# ==========================================
# 4. Model B — Autoencoder with Embeddings
# ==========================================
print("\n--- Preparing Data for Autoencoder ---")
num_scaler = StandardScaler()
num_scaler.fit(normal_train_df[numeric_cols])

# Create Category Encoders (Reserve 0 for 'unknown')
category_maps = {}
category_sizes = {}
for col in categorical_cols:
    values = sorted(train_df[col].astype(str).unique().tolist())
    category_maps[col] = {value: i + 1 for i, value in enumerate(values)}
    category_sizes[col] = len(values) + 1

def prepare_ae_frame(frame):
    numeric = num_scaler.transform(frame[numeric_cols]).astype("float32")
    inputs = {"numeric": numeric}
    targets = {"numeric_out": numeric}
    for col in categorical_cols:
        indices = frame[col].astype(str).map(category_maps[col]).fillna(0).astype("int32").to_numpy()
        inputs[col] = indices
        targets[f"{col}_out"] = indices
    return inputs, targets

ae_train_inputs, ae_train_targets = prepare_ae_frame(normal_train_df)
ae_val_inputs, ae_val_targets = prepare_ae_frame(normal_val_df)
ae_test_inputs, ae_test_targets = prepare_ae_frame(test_df)

print("--- Building Autoencoder Architecture ---")
numeric_input = layers.Input(shape=(len(numeric_cols),), name="numeric")
model_inputs = {"numeric": numeric_input}
parts = [numeric_input]

# Build Embeddings for protocol, service, flag
for col in categorical_cols:
    inp = layers.Input(shape=(), dtype="int32", name=col)
    model_inputs[col] = inp
    emb_dim = min(8, max(2, int(np.ceil(np.sqrt(category_sizes[col])))))
    emb = layers.Embedding(category_sizes[col], emb_dim, name=f"{col}_embedding")(inp)
    parts.append(layers.Flatten()(emb))

combined = layers.Concatenate(name="combined_features")(parts)
hidden = layers.Dense(64, activation="relu")(combined)
latent = layers.Dense(16, activation="relu", name="behavior_embedding")(hidden)
decoded = layers.Dense(64, activation="relu")(latent)

outputs = {
    "numeric_out": layers.Dense(len(numeric_cols), name="numeric_out")(decoded)
}
for col in categorical_cols:
    outputs[f"{col}_out"] = layers.Dense(
        category_sizes[col], activation="softmax", name=f"{col}_out"
    )(decoded)

autoencoder = keras.Model(inputs=model_inputs, outputs=outputs)
encoder = keras.Model(inputs=model_inputs, outputs=latent)

# Define distinct losses
losses = {"numeric_out": "mse"}
loss_weights = {"numeric_out": 1.0}
for col in categorical_cols:
    losses[f"{col}_out"] = "sparse_categorical_crossentropy"
    loss_weights[f"{col}_out"] = 0.35

autoencoder.compile(
    optimizer=keras.optimizers.Adam(learning_rate=1e-3),
    loss=losses,
    loss_weights=loss_weights
)

print("--- Training Autoencoder ---")
callbacks = [
    keras.callbacks.EarlyStopping(monitor="val_loss", patience=5, restore_best_weights=True)
]

history = autoencoder.fit(
    ae_train_inputs, ae_train_targets,
    validation_data=(ae_val_inputs, ae_val_targets),
    epochs=30,
    batch_size=512,
    callbacks=callbacks,
    verbose=1
)

# Scoring Function
def ae_anomaly_scores(model, inputs, targets):
    predictions = model.predict(inputs, verbose=0)
    numeric_error = np.mean(
        np.square(targets["numeric_out"] - predictions["numeric_out"]), axis=1
    )

    categorical_error = np.zeros(len(numeric_error), dtype="float32")
    eps = 1e-8
    for col in categorical_cols:
        true_idx = targets[f"{col}_out"].astype(int)
        probs = predictions[f"{col}_out"]
        categorical_error += -np.log(probs[np.arange(len(true_idx)), true_idx] + eps)

    categorical_error /= len(categorical_cols)
    return numeric_error + 0.35 * categorical_error

normal_val_score = ae_anomaly_scores(autoencoder, ae_val_inputs, ae_val_targets)
ae_score = ae_anomaly_scores(autoencoder, ae_test_inputs, ae_test_targets)

# Threshold set at 95th percentile to adapt to test-set complexity
threshold = np.percentile(normal_val_score, 95)
ae_pred = (ae_score > threshold).astype(int)

# ==========================================
# 5. Quantitative Comparison
# ==========================================
print("\n=== SYSTEMATIC EVALUATION ===")
def metric_row(name, pred):
    precision, recall, f1, _ = precision_recall_fscore_support(
        y_test, pred, average="binary", zero_division=0
    )
    cm = confusion_matrix(y_test, pred)
    tn, fp, fn, tp = cm.ravel()
    return {
        "model": name,
        "precision": precision,
        "recall": recall,
        "f1": f1,
        "false_positives": int(fp),
        "false_negatives": int(fn)
    }

comparison = pd.DataFrame([
    metric_row("Isolation Forest", if_pred),
    metric_row("Autoencoder + Embeddings", ae_pred)
]).set_index("model")

display(comparison.round(3))

# ==========================================
# 6. Inspect Model Disagreements
# ==========================================
results = test_df.copy()
results["if_score"] = if_score
results["if_pred"] = if_pred
results["ae_score"] = ae_score
results["ae_pred"] = ae_pred
results["models_agree"] = results["if_pred"] == results["ae_pred"]

disagreements = results[~results["models_agree"]].copy()
print(f"\nFound {len(disagreements)} disagreements between the models.")
print("Top 10 Disagreements (sorted by AE anomaly score):")

# Display a slice of the most important columns to understand the disagreement
display_cols = ['protocol_type', 'service', 'flag', 'src_bytes', 'dst_bytes', 'is_attack', 'if_pred', 'ae_pred']
display(disagreements.sort_values("ae_score", ascending=False)[display_cols].head(10))



import joblib
import shap

print("=== Phase 1: Saving Models and Preprocessors ===")

# 1. Save Isolation Forest and its preprocessor
joblib.dump(iso, 'isolation_forest.pkl')
joblib.dump(if_preprocessor, 'if_preprocessor.pkl')

# Initialize SHAP explainer for IF and save it (speeds up inference)
explainer_if = shap.TreeExplainer(iso)
joblib.dump(explainer_if, 'explainer_if.pkl')

# 2. Save Autoencoder and its preprocessors
autoencoder.save('autoencoder.keras')
joblib.dump(num_scaler, 'num_scaler.pkl')
joblib.dump(category_maps, 'category_maps.pkl')

print("Models and preprocessors saved successfully!")

import json
import numpy as np
import pandas as pd

print("=== Phase 2: Building the Payload Generator (Sanitized for JSON) ===")

# RAI Metadata (Derived from your evaluation results)
IF_METADATA = {"precision": 0.814, "recall": 0.846, "f1": 0.829, "false_positive_rate": 0.08}
AE_METADATA = {"precision": 0.921, "recall": 0.832, "f1": 0.874, "false_positive_rate": 0.01}

def generate_model_payloads(event_series, event_id):
    # Convert series to a single-row DataFrame for preprocessing
    event_df = pd.DataFrame([event_series])

    # ==========================================
    # 1. Isolation Forest Inference & XAI
    # ==========================================
    x_if = if_preprocessor.transform(event_df[numeric_cols + categorical_cols])
    if_score = float(-iso.decision_function(x_if)[0])
    is_if_alert = int(if_score > 0)

    try:
        # SHAP XAI extraction
        shap_vals = explainer_if.shap_values(x_if)[0]
        if_feat_names = if_preprocessor.get_feature_names_out()
        top_3_if_idx = np.argsort(np.abs(shap_vals))[-3:][::-1]

        # Strictly cast to Python str and float
        if_xai_evidence = {str(if_feat_names[i]): float(shap_vals[i]) for i in top_3_if_idx}
    except Exception as e:
        if_xai_evidence = {"error": "SHAP extraction failed"}

    if_payload = {
        "alert_id": str(event_id),
        "model": "Isolation_Forest",
        "predicted_class": is_if_alert,
        "anomaly_score": float(round(if_score, 4)),
        "xai_top_contributing_features": if_xai_evidence,
        "rai_model_metrics": IF_METADATA
    }

    # ==========================================
    # 2. Autoencoder Inference & XAI
    # ==========================================
    ae_inputs, ae_targets = prepare_ae_frame(event_df)
    ae_score = float(ae_anomaly_scores(autoencoder, ae_inputs, ae_targets)[0])
    is_ae_alert = int(ae_score > threshold)

    # XAI: Feature-level reconstruction error
    ae_preds = autoencoder.predict(ae_inputs, verbose=0)
    numeric_errors = np.square(ae_targets["numeric_out"] - ae_preds["numeric_out"])[0]

    # Map errors to feature names (strictly cast)
    feature_error_dict = {str(numeric_cols[i]): float(numeric_errors[i]) for i in range(len(numeric_cols))}

    # Calculate Cross-Entropy error for categorical features
    eps = 1e-8
    for col in categorical_cols:
        true_idx = int(ae_targets[f"{col}_out"][0])
        prob = float(ae_preds[f"{col}_out"][0][true_idx])
        feature_error_dict[str(col)] = float(-np.log(prob + eps))

    # Get top 3 features with highest reconstruction error
    top_3_ae_features = dict(sorted(feature_error_dict.items(), key=lambda item: item[1], reverse=True)[:3])

    ae_payload = {
        "alert_id": str(event_id),
        "model": "Autoencoder_Embeddings",
        "predicted_class": is_ae_alert,
        "anomaly_score": float(round(ae_score, 4)),
        "threshold": float(round(threshold, 4)), # Explicitly cast numpy.float64 to float
        "xai_feature_reconstruction_errors": top_3_ae_features,
        "rai_model_metrics": AE_METADATA
    }

    return if_payload, ae_payload

print("=== Phase 3: Extracting 4 Specific Scenarios ===")

# Find indices for the 4 scenarios
idx_both_alert = results[(results["if_pred"] == 1) & (results["ae_pred"] == 1)].index[0]
idx_if_only = results[(results["if_pred"] == 1) & (results["ae_pred"] == 0)].index[0]
idx_ae_only = results[(results["if_pred"] == 0) & (results["ae_pred"] == 1)].index[0]
idx_both_normal = results[(results["if_pred"] == 0) & (results["ae_pred"] == 0)].index[0]

scenarios = {
    "SCENARIO 1: Both Models Flagged as Anomaly": idx_both_alert,
    "SCENARIO 2: ONLY Isolation Forest Flagged Anomaly": idx_if_only,
    "SCENARIO 3: ONLY Autoencoder Flagged Anomaly": idx_ae_only,
    "SCENARIO 4: Both Models Flagged as Normal": idx_both_normal
}

for title, idx in scenarios.items():
    print(f"\n{'='*60}\n{title}\n{'='*60}")

    # Get raw event data
    raw_event = test_df.loc[idx]
    event_id = f"evt_{idx}_test"

    # Generate Payloads
    if_json, ae_json = generate_model_payloads(raw_event, event_id)

    print("\n[Isolation Forest Payload]:")
    print(json.dumps(if_json, indent=2))

    print("\n[Autoencoder Payload]:")
    print(json.dumps(ae_json, indent=2))